trigger:
    -master

pool:
    vmImage:'windows-2022'
steps:
  - task: CmdLine@2
    inputs: 
      script: 'dotnet workload install maui'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: 'MyMAUIProject.sln'
    displayName: 'Restore Dependencies'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'MyMAUIProject.sln'
      arguments: '-c Realease -f net6.0-android --verbosity detailed'
    displayName: 'Build Project'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(agent.builddirectory)'
      Contents: '**/*-Signed.aab'
      TargetFolder: '$(build.artifactstagingdirectory)'
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    inputs:
     PathtoPublish: '$(build.ArtifactStagingDirectory)'
     ArtifactName: 'drop'
     publishLocation: 'Container'